---

name: ci
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
  test:
    strategy:
      matrix:
        go_version:
          - '1.11'
          - '1.12'
          - '1.13'
          - '1.14'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
      - name: install
        run: go get -v all
      - name: test
        run: go test -race -cover ./...
